version: '3'
services:
  db:
    hostname: "postgres"
    image: "postgres"
    restart: "always"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata-volume:/var/lib/postgresql/data

  adminer:
          image: adminer
          restart: always
          ports:
              - 5480:8080

volumes:
  pgdata-volume: