version: '3'
services:
  rabbit:
    hostname: "fix-rabbit"
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITUSER}
      - RABBITMQ_DEFAULT_PASS=${RABBITPASSWORD}